version: "3.3"
services:
  nginx:
    image: nhhuy/movie-platform-mosd:nginx-latest
    ports:
      - 5173:5173
    depends_on: 
      - api
    
  api:
    image: nhhuy/movie-platform-mosd:api-latest
    restart: always
    ports:
      - 6234:6234