name: Push BE

on:
  push:
    branches: [ "main" ]
    paths: 
      - api-server/**

  pull_request:
    branches: [ "main" ]
    paths: 
      - api-server/**


jobs:
  build-and-push-be:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./api-server
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_USER }}/movie-platform-mosd:api-latest