name: Deploy server

on:
  workflow_run:
    workflows: ["Push FE", "Push BE"]
    types:
      - completed
  push:
    branches: [ "main" ]
    paths: 
      - ./docker-compose.yml
  pull_request:
    branches: [ "main" ]
    paths: 
      - ./docker-compose.yml

jobs:
  deploy-on-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: SCP docker-compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: ~/

      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            CI=true docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            CI=true docker-compose down 
            CI=true docker images --filter=reference=nhhuy/movie-platform-mosd --format "{{.ID}}" | xargs -I {} docker rmi {}
            CI=true docker-compose build --pull 
            CI=true docker-compose up -d --force-recreate
  
  test-login:
    runs-on: ubuntu-latest

    steps:
      - name: test-login
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            echo "Host connection OK"