name: Push FE

on:
  push:
    branches: [ "main" ]
    paths: 
      - mosd-client/**
  pull_request:
    branches: [ "main" ]
    paths: 
      - mosd-client/**

jobs:
  build-and-push-fe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./mosd-client
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_USER }}/movie-platform-mosd:nginx-latest
